# Launch hyprpal with `--dispatch=socket|hyprctl` to match your environment.
managedWorkspaces:
  # hyprpal will only touch workspaces listed here unless a rule opts out.
  - 3
  - 4
redactTitles: false # set to true to hide client titles from logs and control APIs
gaps:
  inner: 8  # pixels between floating windows
  outer: 20 # pixels around monitor edges
placementTolerancePx: 2.0 # slack for idempotence checks; set 0 for exact matches
modes:
  - name: Coding
    rules:
      - name: Dock comms on workspace 3
        when:
          all:
            - mode: Coding
            - workspace.id: 3
            - apps.present: [Slack, discord]
        actions:
          - type: layout.sidecarDock
            params:
              workspace: 3
              side: right
              widthPercent: 25 # allowed range: 10-50
              match:
                anyClass: [Slack, discord]
      - name: Float design review on workspace 7
        when:
          all:
            - mode: Coding
            - workspace.id: 7
            - app.class: Figma
        allowUnmanaged: true # opt this rule into unmanaged workspace 7
        actions:
          - type: layout.sidecarDock
            params:
              workspace: 7
              side: left
              widthPercent: 30
              match:
                class: Figma
  - name: Gaming
    rules:
      - name: Fullscreen active game
        when:
          mode: Gaming
        allowUnmanaged: true # let fullscreen apply on any workspace
        actions:
          - type: layout.fullscreen
            params:
              target: active
      - name: Force fullscreen for games
        when:
          mode: Gaming
        actions:
          - type: layout.fullscreen
            params:
              target: match
              match:
                titleRegex: "(Proton|Steam|Game)"
