# Launch hyprpal with `--dispatch=socket|hyprctl` to match your environment.
managedWorkspaces:
  # hyprpal will only touch workspaces listed here unless a rule opts out.
  - 3
  - 4
redactTitles: false # set to true to hide client titles from logs and control APIs
gaps:
  inner: 8  # pixels between floating windows
  outer: 20 # pixels around monitor edges
tolerancePx: 2.0 # slack for idempotence checks; set 0 for exact matches
telemetry:
  enabled: false # opt-in anonymous counters (set true to enable)
manualReserved:
  "*":
    top: 0    # defaults applied to all monitors unless overridden below
    right: 0
    bottom: 0
    left: 0
  "DP-1":
    top: 40   # override Hyprland-provided reserved areas (per monitor)
profiles:
  commsDock:
    anyClass: [Slack, discord]
  designReview:
    class: Figma
  fullscreenGames:
    titleRegex: "(Proton|Steam|Game)"
  codingEditor:
    class: code
  codingTerminal:
    anyClass: [Alacritty, kitty]
  codingReference:
    anyClass: [firefox, brave-browser]
modes:
  - name: Coding
    rules:
      - name: Arrange coding grid on workspace 3
        when:
          all:
            - mode: Coding
            - workspace.id: 3
        priority: 5 # optional: higher numbers run earlier when multiple rules match
        actions:
          - type: layout.grid
            params:
              workspace: 3
              # Give the primary column twice the weight of the secondary column
              colWeights: [2, 1]
              # Favor vertical space for the upper row while keeping room for reference docs
              rowWeights: [3, 2]
              slots:
                - name: editor
                  row: 0
                  col: 0
                  # Span both rows so the IDE owns the full-height primary column
                  span:
                    rows: 2
                  match:
                    profile: codingEditor
                - name: terminal
                  row: 0
                  col: 1
                  match:
                    profile: codingTerminal
                - name: reference
                  row: 1
                  col: 1
                  match:
                    profile: codingReference
      - name: Dock comms on workspace 3
        when:
          all:
            - mode: Coding
            - workspace.id: 3
            - apps.present: [Slack, discord]
        actions:
          - type: layout.sidecarDock
            params:
              workspace: 3
              side: right
              widthPercent: 25
              focusAfter: host # keep your editor focused after arranging the dock
              match:
                anyClass: [Slack, discord]
  - name: Gaming
    rules:
      - name: Fullscreen active game
        when:
          mode: Gaming
        mutateUnmanaged: true # let fullscreen apply on any workspace
        actions:
          - type: layout.fullscreen
            params:
              target: active
      - name: Force fullscreen for games
        when:
          mode: Gaming
        actions:
          - type: layout.fullscreen
            params:
              target: match
              match:
                profile: fullscreenGames
